---
title: 'Applied Economic Forecasting'
author: "Put your Name Here"
date: |
    Homework #4a - Spring `r format(Sys.Date(),"%Y")` 
output: pdf_document
header-includes:
 \usepackage{float}
geometry: margin=0.8in
---

```{r setup, include=FALSE}
library(fpp2)
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = 'H') 
theme_set(theme_bw()) #Feel free to change if you like
```

**Instructions**: In all cases, please ensure that your graphs and visuals have properly titles and axes labels, where necessary. For your convenience, I have posted my R markdown file on our course website so that you can open and alter as you see fit. Refer to the output, whenever appropriate, when discussing the results. **Lastly, remember that creativity (coupled with relevance) will be rewarded.**

# Classical Decomposition

**In class, you were exposed to the classical decomposition of an Additive series. Here, I would like you to reproduce that same idea but for a series with a mutiplicative pattern**

1. We will be working with the `plastics` data. Create a time plot of the data to explore its properties. You might find it helpful to use the `help()` function to learn a bit more about the data.


2. Briefly comment on the pattern you observe from your plot in Part 1.

***We are now ready to perform our decomposition. Recall that with a multiplicative decomposition, the functional form is:***

$$Y_t = T_t \times S_t \times R_t $$

Step 1. Using a centered moving average of order 12, calculate the trend, $T_t$ of this model.

Step 2. Compute the detrended variable.

Step 3. Calculate the unadjusted-seasonal component for each month by averaging the detrended value for that season (month). Store this in a variable called `seas.plastic`. You might find it best to assign `seas.plastic` a `NULL` value at the start of your loop.


Step 3b. Now adjust the `seas.plastic` to ensure that it adds up to 12. We can easily achieve this by dividing `seas.plastic` by its mean. Store this as `seas`.


Step 3c. Repeat `seas` to match the length of the series. Besure to declare as a `ts()` object with the appropriate frequency. Remember we lost the first 6 and last 6 values due to the moving average.


Step 4. Lastly, compute the remainder component.

3. Produce the plot of the data and three components as we did in class and store this as `plot1`.


4. Use the `decompose` function to create the **multiplicative** decomposition of the series. Store this plot as `plot2`.


5. Now use the `grid.arrange` command to create a 2 column plot of your two plots stored above.

