---
title: "Writing a Research Paper in Rmd"
thanks: "If you want to add this, otherwise remove..."
author:
- name: This is Me!
  affiliation: Virginia Tech

output: 
  pdf_document:
    citation_package: natbib
    latex_engine: pdflatex
    template: paper-latex-template.tex

abstract: |

 Ideally, this section should be no more than 150 words:
  
    - One or two sentences providing a **basic introduction and background to the problem**. This should not be technical and  understandable to a lay-person.
    
    - One or two sentences telling what you did (in terms of the methodology)
    
    - One or two sentences summarizing the main result (with the words "**here we show**" or their equivalent).
    
    - One or two sentences that indicates the importance of your results. Again, this should not be technical.
    
keywords: "pandoc, r markdown, knitr"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: onehalf
bibliography: "r-references.bib"
biblio-style: apa
---

```{r setup, include = FALSE}
#Include your packages here
```

# Introduction & Background

The Wealth of Nations was published March 9, 1776, [see @R-base] during the Scottish Enlightenment and the Scottish Agricultural Revolution.[e.g. @R-papaja] It influenced several authors and economists, such as Karl Marx, as well as governments and organizations, setting the terms for economic debate and discussion for the next century and a half [@R-base]. For example, Alexander Hamilton was influenced in part by The Wealth of Nations to write his Report on Manufactures, in which he argued against many of Smith's policies. Hamilton based much of this report on the ideas of Jean-Baptiste Colbert, and it was, in part, Colbert's ideas that Smith responded to, and criticized, with The Wealth of Nations. 

@R-base indicates that the Wealth of Nations was the product of seventeen years of notes and earlier works, as well as an observation of conversation among economists of the time concerning economic and societal conditions during the beginning of the Industrial Revolution, and it took Smith some ten years to produce.

*Task: *

- **Add a few citations to your bib file and practice in-text citations.**


# Methodology
## Model Specification

*Task:* 

- **Insert Some Equations**

# Empirical Results
## Data

**Discuss Data Sources here**


## Results

**Discuss the results of your paper here**

# Conclusion

- **What do you conclude?** 
- **What are the implications of your results?**
  - **Who would these results matter to and how has your paper and results helped them?**


\newpage

# References

<div id="refs" custom-style="Bibliography"></div>